# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-24 18:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='name',
            new_name='job_name',
        ),
    ]
